---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-graphite::master]
    - recipe[ktc-gdash::default]
  attributes:
    ha_disabled: true
    etcd:
      addr: 127.0.0.1
      peer_addr: 127.0.0.1
      servers:
        - 127.0.0.1
